name: flutter_painter_example
description: Demonstrates how to use the flutter_painter plugin.
publish_to: 'none'

environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_painter:
    path: ../
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
