name: flutter_painter
description: A new Flutter plugin project.
version: 0.0.1
homepage: null

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  image_picker: ^0.8.7+1
  path_provider: ^2.0.14
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_painter
        pluginClass: FlutterPainterPlugin
      ios:
        pluginClass: FlutterPainterPlugin
