name: flutter_painter
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://github.com/shm40/flutter_painter

environment:
  sdk: ">=2.19.4 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  plugin_platform_interface: ^2.1.6

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.3

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_painter
        pluginClass: FlutterPainterPlugin
      ios:
        pluginClass: FlutterPainterPlugin
